"""Codex global ``AGENTS.md`` renderer.

Writes ``~/.codex/AGENTS.md`` from the workspace identity files. Codex
loads this file at every session start, so the bundle becomes the
agent's effective system prompt for any conversation that runs inside
the configured project.

The bundle is wrapped with:

- a **header** explaining what's in the file and how it got there, and
- a **mandatory-first-action** note pointing at the
  ``session_context()`` MCP tool — Nerve-owned sessions get dynamic
  recall priors injected for free; Codex sessions have to fetch them
  with a tool call.
"""

from __future__ import annotations

from pathlib import Path

from nerve.external_agents.registry import FileTarget
from nerve.external_agents.renderers.base import (
    SECTION_DIVIDER,
    StyleRenderer,
    read_workspace_file,
)


HEADER = """\
# Codex AGENTS.md — Generated by Nerve

This file is auto-rendered by Nerve's external-agents sync service. It
bundles your workspace identity files (SOUL, USER, IDENTITY, TOOLS,
MEMORY) so Codex sessions inherit the same context Nerve-owned sessions
get from their system prompt.

> ⚠️ **Edits will be overwritten** on the next sync run. To change what
> appears here, edit the source files in your Nerve workspace.
"""

FIRST_ACTION = """\
# Mandatory First Action — Call `session_context()`

Before answering anything in a fresh thread, call the Nerve MCP tool
`session_context(topic="<what you're about to do>")`. It returns the
dynamic context that Nerve-owned sessions receive automatically:

- Recalled memories from memU, biased by the topic you pass
- A summary of currently active skills
- Available workflow-preset strategies when that MCP capability is served
- Session metadata (id, source, current time)

Skip this and you'll be working blind: the static bundle below is the
*identity prior*, but the *recall prior* (priors learned from past
conversations) lives in memU and only surfaces through this tool.

If `session_context` is unavailable (MCP not configured, network error)
just say so and continue — don't pretend you have priors you don't.
"""


class CodexGlobalRenderer(StyleRenderer):
    """Render the Codex global ``AGENTS.md``.

    Layout:

    ```
    <HEADER>
    ---
    <FIRST_ACTION>
    ---
    # SOUL.md
    ...
    ---
    # IDENTITY.md
    ...
    ---
    ...
    ```
    """

    def render(self, target: FileTarget, *, workspace: Path) -> str:
        parts: list[str] = [HEADER.rstrip(), FIRST_ACTION.rstrip()]
        body = self._concat_includes(target, workspace, with_headings=True)
        if body:
            parts.append(body)

        footer = self._render_footer(workspace)
        if footer:
            parts.append(footer)

        return SECTION_DIVIDER.join(parts).rstrip() + "\n"

    # ---- Internals ------------------------------------------------

    def _render_footer(self, workspace: Path) -> str:
        """Short footer reminding the agent how to keep memory hot.

        We also surface the workspace path so the agent doesn't have
        to guess it from environment variables.
        """
        return (
            "# Workspace\n\n"
            f"- **Path:** `{workspace}`\n"
            "- **Memory updates:** Use the `memorize` MCP tool to save "
            "important facts; Nerve's daily maintenance cron will dedupe "
            "and refine them automatically.\n"
            "- **Recall:** Use `memory_recall(query)` to search past "
            "conversations and saved facts.\n"
        )

    # Used by tests / debugging — not part of the public interface.
    def _render_section(self, workspace: Path, filename: str) -> str:
        content = read_workspace_file(workspace, filename)
        if not content.strip():
            return ""
        return f"# {filename}\n\n{content.strip()}\n"
