import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Loader2, Play, Square, Workflow } from 'lucide-react';
import { api, type PresetWorkflow, type WorkflowPreset, type WorkflowPresetSummary } from '../api/client';

const active = new Set(['queued', 'running', 'cancelling']);
function duration(from?: string | null, until?: string | null) { if (!from) return '—'; const s = Math.max(0, Math.floor(((until ? Date.parse(until) : Date.now()) - Date.parse(from)) / 1000)); return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`; }

function Launch({ summary, onStarted }: { summary: WorkflowPresetSummary; onStarted: () => void }) {
  const [preset, setPreset] = useState<WorkflowPreset | null>(null); const [inputs, setInputs] = useState<Record<string, unknown>>({}); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const open = async () => { if (!preset) { try { setPreset(await api.getWorkflowPreset(summary.name)); } catch (e) { setError(String(e)); } } else setPreset(null); };
  const start = async () => { setBusy(true); setError(''); try { await api.validateWorkflowPreset(summary.name, inputs); await api.startWorkflowPreset(summary.name, inputs); setPreset(null); onStarted(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  return <div className="rounded-lg border border-border-subtle bg-surface p-3"><button onClick={() => void open()} className="w-full text-left cursor-pointer"><div className="font-medium text-[13px] text-text-secondary">{summary.title}</div><div className="mt-1 text-[11px] text-text-dim">{summary.description || summary.name} · {summary.stages} stages · v{summary.version}</div></button>{preset && <div className="mt-3 border-t border-border-subtle pt-3 space-y-2">{Object.entries(preset.inputs).map(([name, schema]) => <label key={name} className="block text-[11px] text-text-muted">{schema.title || name}<input className="mt-1 w-full rounded border border-border bg-bg px-2 py-1 text-text" value={String(inputs[name] ?? schema.default ?? '')} onChange={e => setInputs(v => ({ ...v, [name]: schema.type === 'number' ? Number(e.target.value) : e.target.value }))} /></label>)}<div className="text-[10px] text-text-faint">Budget ${preset.budget_usd.toFixed(2)} · timeout {preset.timeout_seconds}s · pinned on start</div>{error && <div className="text-[11px] text-hue-red">{error}</div>}<button disabled={busy} onClick={() => void start()} className="inline-flex items-center gap-1 rounded bg-accent px-2 py-1 text-[11px] text-white disabled:opacity-50 cursor-pointer">{busy ? <Loader2 size={11} className="animate-spin" /> : <Play size={11} />} Validate & start</button></div>}</div>;
}

function WorkflowCard({ workflow, reload }: { workflow: PresetWorkflow; reload: () => void }) { const [stopping, setStopping] = useState(false); const stop = async () => { setStopping(true); try { await api.cancelPresetWorkflow(workflow.id); reload(); } finally { setStopping(false); } }; return <div className="rounded-lg border border-border-subtle bg-surface p-3"><div className="flex gap-2"><Workflow size={16} className="text-hue-violet shrink-0"/><div className="min-w-0 flex-1"><div className="text-[13px] text-text-secondary">{workflow.preset.title} <span className="font-mono text-[10px] text-text-faint">{workflow.id}</span></div><div className="text-[10px] text-text-faint">{workflow.status} · v{workflow.preset.version} · {workflow.preset_hash.slice(0, 12)} · {duration(workflow.started_at, workflow.finished_at)}</div></div>{active.has(workflow.status) && <button onClick={() => void stop()} disabled={stopping} className="inline-flex h-fit items-center gap-1 rounded border border-red-400/30 px-2 py-1 text-[10px] text-hue-red cursor-pointer"><Square size={10}/> Stop</button>}</div><div className="mt-3 space-y-1">{workflow.stages.map(stage => <div key={stage.id} className="flex items-center gap-2 rounded bg-bg-sunken px-2 py-1 text-[11px]"><span className="font-mono text-text-secondary">{stage.stage_id}</span><span className="text-text-faint">{stage.runner === 'agent' ? 'agent stage' : 'execution stage'}</span><span className="ml-auto text-text-muted">{stage.status}</span>{stage.child_type === 'execution' && stage.child_id && <Link className="text-accent" to={`/chat/${workflow.owner_session_id}`}>execution</Link>}</div>)}</div></div> }

export function PresetWorkflowsPage() { const [presets, setPresets] = useState<WorkflowPresetSummary[]>([]); const [workflows, setWorkflows] = useState<PresetWorkflow[]>([]); const [loading, setLoading] = useState(true); const load = async () => { try { const [p, w] = await Promise.all([api.listWorkflowPresets(), api.listPresetWorkflows()]); setPresets(p.presets); setWorkflows(w.workflows); } finally { setLoading(false); } }; useEffect(() => { void load(); const id = window.setInterval(() => void load(), 15000); return () => clearInterval(id); }, []); if (loading) return <div className="h-full grid place-items-center"><Loader2 className="animate-spin"/></div>; return <div className="h-full overflow-auto p-6"><h1 className="text-lg font-semibold text-text">Preset workflows</h1><p className="mt-1 text-[12px] text-text-dim">Reviewed, pinned stages. Prompts, secrets, skills and unbounded logs are not shown here.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{presets.map(p => <Launch key={p.name} summary={p} onStarted={() => void load()}/>)}</div><h2 className="mt-7 text-sm font-medium text-text-secondary">Runs</h2><div className="mt-3 space-y-2">{workflows.map(w => <WorkflowCard key={w.id} workflow={w} reload={() => void load()}/>)}{!workflows.length && <div className="text-[12px] text-text-faint">No preset workflows yet.</div>}</div></div> }
